first_app_blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('offshore_blog.urls', namespace='offshore_blog')),
    path('admin/', admin.site.urls),
]

offshore_blog/urls.py
from django.urls import path, reverse
from django.views.generic import TemplateView

from . import views


app_name = 'offshore_blog'

urlpatterns = [
    # path('', views.ArticleList.as_view()),
    path('', views.index, name='index'),
    path('article/<int:article_id>/', views.ArticlePage.as_view(), name='page_article'),
    path('search', views.search_outcome, name='search_result'),
]

offshore_blog/models.py
from django.db import models
from django.db.models import F
from mptt.models import MPTTModel, TreeForeignKey


class ArticleManager(models.Manager):
    @staticmethod
    def top_articles(limit=5):
        return Article.objects.order_by('-page_views')[:limit]


class CommentManager(models.Manager):
    @staticmethod
    def last_5_comments(limit=5):
        return Comment.objects.order_by('-pub_date')[:limit]


class Article(models.Model):
    head_article = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField()
    page_views = models.IntegerField(default=0)
    objects = ArticleManager()

    def increment(self):
        Article.objects.filter(id=self.pk).update(page_views=F('page_views') + 1)

    def __str__(self):
        return self.head_article

    def get_absolute_url(self):
        return u'' % self.id


class Comment(MPTTModel):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments', null=True)
    name = models.CharField(max_length=100)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    objects = CommentManager()

    class MPTTMeta:
        order_insertion_by = ['pub_date']

    def __str__(self):
        return self.content

offshore_blog/views.py
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from . import form
from .models import Article, Comment

from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView


# class ArticleList(ListView):
#     model = Article
#     template_name = 'offshore_blog/index.html'
#     paginate_by = 3
#     context_object_name = "articles"
#
#     def get_queryset(self):
#         return Article.objects.all()
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['articles'] = Article.objects.all()
#         context['article_views'] = Article.objects.top_articles()
#         context['5_last_comments'] = Comment.objects.last_5_comments()
#         return context


def index(request):
    """This view function returns html text for articles list"""
    all_articles = Article.objects.all()
    paginator = Paginator(all_articles, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'articles': Article.objects.all(),
        'article_views': Article.objects.top_articles(),
        '5_last_comments': Comment.objects.last_5_comments(),
    }
    return render(request, 'offshore_blog/index.html', context)


class ArticlePage(FormView):
    template_name = 'offshore_blog/article.html'
    form_class = form.CommentForm
    success_url = ''

    def get_context_data(self, **kwargs):

        comment_form = form.CommentForm()

        context = super().get_context_data(**kwargs)
        context['article'] = get_object_or_404(Article, pk=self.kwargs['article_id'])
        context['comments'] = Comment.objects.filter(post_id=self.kwargs['article_id'])
        context['article_views'] = Article.objects.top_articles()
        context['5_last_comments'] = Comment.objects.last_5_comments()
        context['comment_form'] = comment_form

        if self.request.method == "GET":
            context['article'].increment()
        elif self.request.method == "POST":
            comment_form = form.CommentForm(self.request.POST)
            if comment_form.is_valid():
                user_comment = comment_form.save(commit=False)
                user_comment.post = context['article']
                user_comment.save()
                return HttpResponseRedirect(reverse('page_article', args=[context['article']]))
        return context



# def page_article(request, article_id):
#     """This view function returns html text for particular article"""
#     article = get_object_or_404(Article, pk=article_id)
#     comments = Comment.objects.filter(post_id=article_id)
#     # comment = Comment.objects.
#     # old solution
#     # Article.objects.filter(pk=article_id).update(page_views=F('page_views') + 1)
#     # article_views = Article.objects.order_by('-page_views')[:5]
#     # old solution
#     comment_form = form.CommentForm()
#     """increment article views counter"""
#     if request.method == "GET":
#         article.increment()
#     elif request.method == "POST":
#         comment_form = form.CommentForm(request.POST)
#         if comment_form.is_valid():
#             user_comment = comment_form.save(commit=False)
#             user_comment.post = article
#             user_comment.save()
#             return HttpResponseRedirect(reverse('page_article', args=[article_id]))
#
#     # prepare view context
#     context = {
#         'article': article,
#         'article_views': Article.objects.top_articles(),
#         'comments': comments,
#         '5_last_comments': Comment.objects.last_5_comments(),
#         'comment_form': comment_form,
#     }
#     return render(request, 'offshore_blog/article.html', context)


def search_outcome(request):
    context = {
        'article_views': Article.objects.top_articles(),
        '5_last_comments': Comment.objects.last_5_comments(),
    }
    return render(request, 'offshore_blog/search_result.html', context)

offshore_blog/templates/offshore_blog/article.html
{% load static %}
{% load mptt_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
    <link rel="stylesheet" href="{% static 'offshore_blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'offshore_blog/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'offshore_blog/css/article.css' %}">
    <link rel="stylesheet" href="{% static 'offshore_blog/css/common.css' %}">
</head>
<body>

<!--Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-success bg-gradient">
    <div class="container">
        <a href="#" class="navbar-brand">Daily news</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse4">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse4">
            <div class="navbar-nav">
                <a href="#" class="nav-item nav-link">Home</a>
                <a href="#" class="nav-item nav-link">About</a>
            </div>
            <form class="d-flex ms-auto">
                <input type="text" class="form-control me-sm-2" placeholder="Search">
                <button type="submit" class="btn btn-outline-light">Search</button>
            </form>
        </div>
    </div>
</nav>
<!--Navigation-->


<div class="container">

    <div class="row">
        <div class="col-8">
            {% include 'offshore_blog/article_page_template.html' %}
            {% include 'offshore_blog/comments.html' %}
        </div>
        <div class="col-4">
            {% include 'offshore_blog/top5_articles.html' %}
            {% include 'offshore_blog/last_comments.html' %}
        </div>
    </div>

</div>
</body>
</html>

offshore_blog/templates/offshore_blog/article_list_template.html
{% load static %}


{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">next</a>
{% endif %}


{% for article in articles %}
<div>
    <div class="head_art"><h4>{{ article.head_article }} </h4></div>
    <div class="article"><p>{{ article.content | truncatewords:75 }}</p></div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a href="{% url 'offshore_blog:page_article' article.id %}" class="btn btn-success" role="button" data-bs-toggle="button">Read</a>
    </div>
    <div class="content_article"><p>Views: {{ article.page_views }}</p></div>
</div>
{% endfor %}




<br><br><br><br>


<!--<div>-->
<!--    <ul>-->
<!--    {% for p in paginator.page_range %}-->
<!--    <li>-->
<!--        <a href="?page={{ p }}">{{ p }}</a>-->
<!--    </li>-->
<!--    {% endfor %}-->
<!--    </ul>-->
<!--</div>-->

offshore_blog/templates/offshore_blog/article_page_template.html
{% load static %}

<div>
    <div class="head_article"><p>{{ article.head_article }}</p></div>
    <div class="content_article"><p>{{ article.content }}</p></div>
    <div class="content_article"><p>Views: {{ article.page_views }}</p></div>
</div>

offshore_blog/templates/offshore_blog/comments.html
{% load static %}
{% load mptt_tags %}

<div class="block_comments">
  <ul>
    {% recursetree comments %}
    <li>
      <div id="{{ node.id }}">Comment by {{ node.name }}: <p>{{ node.content }}</p></div>
<!--      <div>{{ node.id }}</div>-->
<!--      <button class="btn btn-success" onclick="myFunction({{ node.id }})">Reply</button>-->
      {% if not node.is_leaf_node %}
      <ul>{{ children }}</ul>

      {% endif %}
    </li>
    {% endrecursetree %}
  </ul>
</div>


<div class="form_for_comments">
  <form method="POST">
  {% csrf_token %}
  {{ comment_form }}
  <div class="mb-3">
    <input name="submit" type="submit" id="submit" class="btn btn-success" value="Submit Comment">
  </div>
</form>
</div>

offshore_blog/templates/offshore_blog/index.html
{% load static %}
<!---->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
    <link rel="stylesheet" href="{% static 'offshore_blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'offshore_blog/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'offshore_blog/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'offshore_blog/css/common.css' %}">
</head>
<body>

<!--Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-success bg-gradient">
    <div class="container">
        <a href="#" class="navbar-brand">Daily news</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse4">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse4">
            <div class="navbar-nav">
                <a href="#" class="nav-item nav-link">Home</a>
                <a href="#" class="nav-item nav-link">About</a>
            </div>
            <form class="d-flex ms-auto" method="POST">
                 {% csrf_token %}
                <input type="text" class="form-control me-sm-2" placeholder="Search" name="search">
                <button type="submit" class="btn btn-outline-light">Search</button>
            </form>
<!--Search function will be implemented in the future-->
        </div>
    </div>
</nav>
<!--Navigation-->


<div class="container">

    <div class="row">
        <div class="col-8">
            {% include 'offshore_blog/article_list_template.html' %}
        </div>
        <div class="col-4">
            {% include 'offshore_blog/top5_articles.html' %}
            {% include 'offshore_blog/last_comments.html' %}
        </div>
    </div>
</div>
</body>
</html>

offshore_blog/templates/offshore_blog/last_comments.html
{% load static %}


<div class="block_top_five">
    <div><p>LAST 5 COMMENTS</p></div>
    <div>
        {% for comment in 5_last_comments %}
        <a class=" list-group-item list-group-item-action" href="{% url 'offshore_blog:page_article' comment.post_id %}">
        <p>{{ comment.content | truncatewords:8 }}</p>
            <p>{{ comment.pub_date | date:"Y-m-d H:i:s" }}</p>
        </a>
        {% endfor %}

    </div>
</div>

offshore_blog/templates/offshore_blog/search_result.html
{% load static %}
<!---->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
    <link rel="stylesheet" href="{% static 'offshore_blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'offshore_blog/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'offshore_blog/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'offshore_blog/css/common.css' %}">
</head>
<body>

<!--Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-success bg-gradient">
    <div class="container">
        <a href="" class="navbar-brand">Daily news</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse4">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse4">
            <div class="navbar-nav">
                <a href="#" class="nav-item nav-link">Home</a>
                <a href="#" class="nav-item nav-link">About</a>
            </div>



            <form class="d-flex ms-auto" method="POST">
                 {% csrf_token %}

                <input type="text" class="form-control me-sm-2" placeholder="Search" name="search">


                <button type="submit" class="btn btn-outline-light">Search</button>
            </form>
        </div>
    </div>
</nav>
<!--Navigation-->


<div class="container">

    <div class="row">
        <div class="col-8">
            {% include 'offshore_blog/search_result_template.html' %}
        </div>
        <div class="col-4">
            {% include 'offshore_blog/top5_articles.html' %}
            {% include 'offshore_blog/last_comments.html' %}
        </div>
    </div>
</div>
</body>
</html>

offshore_blog/templates/offshore_blog/search_result_template.html
{% load static %}

offshore_blog/templates/offshore_blog/top5_articles.html
{% load static %}

<div class="block_top_five">
    <p>TOP 5 ARTICLES</p>
{% for article in article_views %}
    <div>
        <a class=" list-group-item list-group-item-action" href="{% url 'offshore_blog:page_article' article.id %}"><p><strong>{{ article.head_article | truncatewords:8 }}</strong></p></a>
    </div>
{% endfor %}
</div>